# Generated by Django 4.1.6 on 2023-02-10 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartoons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('image', models.ImageField(upload_to='static/app/img', verbose_name='Постер')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('video', models.FileField(upload_to='static/app/video', verbose_name='Видео')),
                ('wiki', models.TextField(verbose_name='Подробнее о фильме')),
                ('poster', models.ImageField(upload_to='static/app/img', verbose_name='Превью')),
                ('year_n_duration', models.CharField(max_length=255, verbose_name='Год и продолжительность')),
                ('rating', models.CharField(max_length=10, verbose_name='Рейтинг (IMDb)')),
            ],
            options={
                'verbose_name': 'Cartoon',
                'verbose_name_plural': 'Cartoons',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('image', models.ImageField(upload_to='static/app/img', verbose_name='Постер')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('video', models.FileField(upload_to='static/app/video', verbose_name='Видео')),
                ('wiki', models.TextField(verbose_name='Подробнее о фильме')),
                ('poster', models.ImageField(upload_to='static/app/img', verbose_name='Превью')),
                ('year_n_duration', models.CharField(max_length=255, verbose_name='Год и продолжительность')),
                ('rating', models.CharField(max_length=10, verbose_name='Рейтинг (IMDb)')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.country')),
                ('dislikes', models.ManyToManyField(related_name='m_dislikes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Films',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=20, verbose_name='Название жанра')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('image', models.ImageField(upload_to='static/app/img', verbose_name='Постер')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('video', models.FileField(upload_to='static/app/video', verbose_name='Видео')),
                ('wiki', models.TextField(verbose_name='Подробнее о фильме')),
                ('poster', models.ImageField(upload_to='static/app/img', verbose_name='Превью')),
                ('year_n_duration', models.CharField(max_length=255, verbose_name='Год и продолжительность')),
                ('rating', models.CharField(max_length=10, verbose_name='Рейтинг (IMDb)')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.country')),
                ('dislikes', models.ManyToManyField(related_name='s_dislikes', to=settings.AUTH_USER_MODEL)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.genre')),
                ('likes', models.ManyToManyField(related_name='s_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Series',
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.CreateModel(
            name='SeriesReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('s_email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('s_text', models.TextField(verbose_name='Ваш отзыв')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.series', verbose_name='Сериал')),
            ],
            options={
                'verbose_name': 'Series Review',
                'verbose_name_plural': 'Series Reviews',
            },
        ),
        migrations.CreateModel(
            name='FilmsReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('m_email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('m_text', models.TextField(verbose_name='Ваш отзыв')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.films', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Films Review',
                'verbose_name_plural': 'Films Reviews',
            },
        ),
        migrations.AddField(
            model_name='films',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.genre'),
        ),
        migrations.AddField(
            model_name='films',
            name='likes',
            field=models.ManyToManyField(related_name='m_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CartoonsReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('c_email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('c_text', models.TextField(verbose_name='Ваш отзыв')),
                ('cartoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.cartoons', verbose_name='Мультфильм')),
            ],
            options={
                'verbose_name': 'Cartoons Review',
                'verbose_name_plural': 'Cartoons Reviews',
            },
        ),
        migrations.AddField(
            model_name='cartoons',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.country'),
        ),
        migrations.AddField(
            model_name='cartoons',
            name='dislikes',
            field=models.ManyToManyField(related_name='c_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartoons',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.genre'),
        ),
        migrations.AddField(
            model_name='cartoons',
            name='likes',
            field=models.ManyToManyField(related_name='c_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
