# Generated by Django 4.1.6 on 2023-02-09 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('image', models.ImageField(upload_to='static/app/img', verbose_name='Постер')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('video', models.FileField(upload_to='static/app/video', verbose_name='Видео')),
                ('wiki', models.TextField(verbose_name='Подробнее о фильме')),
                ('poster', models.ImageField(upload_to='static/app/img', verbose_name='Превью')),
                ('year_n_duration', models.CharField(max_length=255, verbose_name='Год и продолжительность')),
                ('rating', models.CharField(max_length=10, verbose_name='Рейтинг (IMDb)')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.country')),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Films',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=20, verbose_name='Название жанра')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('image', models.ImageField(upload_to='static/app/img', verbose_name='Постер')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('video', models.FileField(upload_to='static/app/video', verbose_name='Видео')),
                ('wiki', models.TextField(verbose_name='Подробнее о фильме')),
                ('poster', models.ImageField(upload_to='static/app/img', verbose_name='Превью')),
                ('year_n_duration', models.CharField(max_length=255, verbose_name='Год и продолжительность')),
                ('rating', models.CharField(max_length=10, verbose_name='Рейтинг (IMDb)')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.country')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.genre')),
            ],
            options={
                'verbose_name': 'Series',
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.films')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='films',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.genre'),
        ),
        migrations.CreateModel(
            name='Cartoons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('image', models.ImageField(upload_to='static/app/img', verbose_name='Постер')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('video', models.FileField(upload_to='static/app/video', verbose_name='Видео')),
                ('wiki', models.TextField(verbose_name='Подробнее о фильме')),
                ('poster', models.ImageField(upload_to='static/app/img', verbose_name='Превью')),
                ('year_n_duration', models.CharField(max_length=255, verbose_name='Год и продолжительность')),
                ('rating', models.CharField(max_length=10, verbose_name='Рейтинг (IMDb)')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.country')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.genre')),
            ],
            options={
                'verbose_name': 'Cartoon',
                'verbose_name_plural': 'Cartoons',
            },
        ),
    ]
