# Generated by Django 4.1.6 on 2023-02-18 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_filmsreview_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmsreview',
            name='date',
        ),
    ]
