# Generated by Django 4.1.6 on 2023-03-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_filmsreview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoonsreview',
            name='c_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='filmsreview',
            name='m_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='seriesreview',
            name='s_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Электронная почта'),
        ),
    ]
