# Generated by Django 4.1.6 on 2023-03-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_cartoonsreview_c_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoonsreview',
            name='c_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='filmsreview',
            name='m_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='seriesreview',
            name='s_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта'),
        ),
    ]
